### ISSUE TITLE
"onlyChanged" mode

### ISSUE THREAD

**Issue by fax1ty** [almond-bongbong/react-slot-counter#1]
Please add the option not to scroll through the numbers that have not changed

ex. 12345 + 1 = 12346
1234 should not be animated

**Comment by almond-bongbong** [comment]
Thank you for your suggestion! We really appreciate your feedback. We will add this feature soon to ensure that only the changed numbers are animated. Stay tuned for updates!

**Comment by almond-bongbong** [comment]
I've adopted your suggested feature as the default behavior. Now, only the changed numbers or characters will be animated.
However, if you prefer not to use this feature, you can pass animateUnchanged: true as a prop. The default value is false.
These changes are included in version 1.4.0.
