### ISSUE TITLE
dummyCharacterCount={1}

### ISSUE THREAD

**Issue by Konstantin9658** [almond-bongbong/react-slot-counter#10]
Hello! Long time no see 😁

I noticed a small bug related to dummyCharacterCount. When its value is 1, then the following happens: the value in the counter will first increase by 1 and then the counter will scroll through this digit. Is there a way to fix this?

https://github.com/almond-bongbong/react-slot-counter/assets/76180339/e5557486-7a79-4675-a0b1-c1a9f95ca8de

**Comment by Konstantin9658** [comment]
perhaps this is not a bug, but I would like it to work as follows: we don’t know in advance how much the counter can increase, but maybe there is a possibility to somehow dynamically find out by how much the number has increased? What I mean: suppose we have 105 coins on the balance, when I raise a coin worth 3, I will see how 6-> 7-> 8 is spinning, not random numbers

**Comment by almond-bongbong** [comment]
Hello, as always, thank you for your contribution!

Your suggestion seems like a brilliant idea! It's a feature that can potentially benefit many users. After analyzing your request, we will proceed with the development, but I anticipate we might add a prop to dynamically show the increase or decrease instead of random numbers.

I appreciate you bringing this good idea to our attention. We'll get started on the update. Thanks again!

**Comment by Konstantin9658** [comment]
Thank you very nice to hear! I'm looking forward to the soonest update, if there are additional questions, write - I'm monitoring the repository!

**Comment by almond-bongbong** [comment]
Thank you! I've added the `sequentialAnimationMode` feature which now allows for the changes in numbers to be displayed sequentially. Also, I left a brief thank-you comment on the demo page to express our gratitude for your contribution. If I've made you feel uncomfortable by mentioning you without permission, I sincerely apologize. Please let me know if you felt even a little bit upset.

Thank you once again.

![image](https://github.com/almond-bongbong/react-slot-counter/assets/42146674/c8460450-65f4-475f-b6e1-8497b0b287e2)

**Comment by Konstantin9658** [comment]
Hooray! Thank you for your work, I am very pleased that my ideas are useful. Thanks again!

**Comment by Konstantin9658** [comment]
@almond-bongbong By the way, as an improvement option, you can add a throttle so that the animation does not play when we raise, for example, 5 coins in a row (to understand what I mean, you need to click on +1 five times in a row on the demo page and you will see). Everything else is just great!

**Comment by almond-bongbong** [comment]
@Konstantin9658  That's a great suggestion! I'll definitely consider this and explore the best way to implement throttle or debounce in future updates. Thank you for your continued feedback and support!
