### ISSUE TITLE
export 'SlotCounterRef' (imported as 'SlotCounterRef') was not found in 'react-slot-counter' (possible exports: default)

### ISSUE THREAD

**Issue by RDETB07** [almond-bongbong/react-slot-counter#13]
Getting this error. I created a new react app and simply installed this component and it's treating "SlotCounterRef" never existed?

"import SlotCounter, { SlotCounterRef } from 'react-slot-counter';" - This is from the github page example

ERROR in ./src/components/SlotMachine.js 9:30-44

export 'SlotCounterRef' (imported as 'SlotCounterRef') was not found in 'react-slot-counter' (possible exports: default)

..

That being said I only have react js + node js installed here

**Comment by almond-bongbong** [comment]
I apologize for the confusion. SlotCounterRef is needed for the TypeScript example. If you're working on a project using JavaScript, you won't need SlotCounterRef.

**Comment by RDETB07** [comment]
Works perfectly now. Thank you :)
