### ISSUE TITLE
sequentialAnimationMode?

### ISSUE THREAD

**Issue by misstricky** [almond-bongbong/react-slot-counter#19]
Hi! Great library! I could just be misunderstanding the settings but wanted to mention this just incase. 

My goal is essentially to start with 0 (`startValue`) and increment sequentially until it reaches my `value` of "230,436" -- but when I have these settings in my component:
```
<SlotCounter
    ref={counterRef}
    startValue={0}
    sequentialAnimationMode
    charClassName="actions-taken-number"
    separatorClassName="actions-taken-number"
    value="230,436"
/>
```

But with those settings, I don't really see any animation,  I just see this extremely large number on load:
![image](https://github.com/almond-bongbong/react-slot-counter/assets/353156/a738ebe9-f4d1-48ba-a47a-cd4688714dac)

If I take out `sequentialAnimationMode`, so these settings in my component:
```
<SlotCounter
    ref={counterRef}
    startValue={0}
    charClassName="actions-taken-number"
    separatorClassName="actions-taken-number"
    value="230,436" 
/>
```

Then I see the animation and the `value` that is set when the animiation completes (instead of the incorrect massive number in the screenshot above):
![image](https://github.com/almond-bongbong/react-slot-counter/assets/353156/0bf41e3d-7450-412f-a884-3167cf57608a)

Is there a way for me to to start with 0 (`startValue`) and increment sequentially until it reaches my `value` of "230,436", where "230,436" is visible at the end of the animation? Thanks!!

**Comment by almond-bongbong** [comment]
Thank you for bringing this issue to our attention and for the detailed explanation. Your feedback is invaluable for improving the library.

I'll be looking into this issue promptly to diagnose the cause and find a suitable solution.

Thanks again

**Comment by almond-bongbong** [comment]
We've addressed the issue of numbers appearing duplicated and the animation behavior in version 1.15.0. However, the current fix may not exactly align with what you were expecting. We are planning to make further improvements while considering compatibility with other options. At this stage, we may not have a perfect solution for your specific needs, and for that, we apologize.

Thank you for your understanding!

**Comment by misstricky** [comment]
Thank you for looking into it! You're right, now it does not double the numbers, but yeah there is no animation -- will try again when theres further changes -- thank you!

**Comment by misstricky** [comment]
This is working better for me after the 2.0 update!

**Comment by almond-bongbong** [comment]
Good!
