### ISSUE TITLE
Infinite dummy list

### ISSUE THREAD

**Issue by blzpedro** [almond-bongbong/react-slot-counter#2]
Hey, I was taking a look into your lib then I thought of one suggestion, you could create an "infinite" dummy list with the real value centralized just adding the dummy list to the bottom. 

What do you think?

**Comment by almond-bongbong** [comment]
Thank you very much for your suggestion! I appreciate your input, and I'll start working on implementing this feature right away. 🙂

**Comment by blzpedro** [comment]
Nice, thanks!

I'm trying to implement this and if it works I open a PR for your repo!

**Comment by blzpedro** [comment]
Hey, I opened a PR, can you see it there? 

https://github.com/almond-bongbong/react-slot-counter/pull/3

**Comment by almond-bongbong** [comment]
Yes, thank you! I'll check out the PR.

**Comment by blzpedro** [comment]
Seems that it's resolved. Added the prop hasInfiniteList.
