### ISSUE TITLE
Issue in autoAnimationStart

### ISSUE THREAD

**Issue by divy-bst** [almond-bongbong/react-slot-counter#20]
Even if we set the value of autoAnimationStart={false} , initial animation is happening on every render of the component.
I want to only animate it on click of a button.What is the solution for this?

**Comment by almond-bongbong** [comment]
Thank you for bringing this issue to our attention. I will investigate the behavior of the autoAnimationStart property immediately and aim to resolve the issue as quickly as possible.

**Comment by almond-bongbong** [comment]
This issue has been fixed in version 2.0.0. It was a significant bug, and I appreciate you bringing it to my attention. Feel free to share any more feedback or concerns at any time.

Thank you.
