### ISSUE TITLE
🐛 useMonospaceWidth

### ISSUE THREAD

**Issue by Konstantin9658** [almond-bongbong/react-slot-counter#21]
Hi @almond-bongbong !

When I use this props last number not use monospace width.

You might think that it is limited by the container, but no. The same happens with any container width.

![image](https://github.com/almond-bongbong/react-slot-counter/assets/76180339/6b5a913c-5b97-4e2f-aa00-aad1e9b51778)
![image](https://github.com/almond-bongbong/react-slot-counter/assets/76180339/e81cf0e2-e98b-416a-a417-0c5a2c0d213d)

**Comment by almond-bongbong** [comment]
I've improved the `width` calculation logic in version 2.0.1. If you encounter any other issues, please feel free to let me know. Thank you.

**Comment by Konstantin9658** [comment]
the problem seems to have gone away, but I came across this bug, it seems it didn’t calculate the width

![image](https://github.com/almond-bongbong/react-slot-counter/assets/76180339/288cddb4-f0d1-4338-8f39-f65e7d4320d2)

**Comment by almond-bongbong** [comment]
I apologize for the inconvenience. I would like to investigate this issue further. 🤔
If you have a live page where I can check this, it would be even more helpful. Thank you!

**Comment by almond-bongbong** [comment]
If you're using the `valueClassName` prop, we've fixed a related width calculation issue in version 2.0.2. If you find that the issue persists, it would be immensely helpful if you could share the props or code you are using for me to better understand the issue.

I really appreciate your keen interest in reporting this issue. Thank you! 👍

**Comment by Konstantin9658** [comment]
```jsx
const Balance = () => {
  const { balance } = useBank();
  useEffect(() => {
    balance;
  }, [balance]);

  return (
    <div className={classes.container}>
      <img srcSet={`${mercoin} 1x, ${mercoin2x} 2x`} alt="" />
      <SlotCounter
        value={balance}
        sequentialAnimationMode
        valueClassName={classes.char}
        duration={0.3}
        debounceDelay={100}
        charClassName={classes.char}
        useMonospaceWidth
      />
    </div>
  );
};

export const BalanceBoard = ({ className }: { className?: string }) => {
  const [widthBoard, setWidthBoard] = useState(110);

  const { balance } = useBank();

  useEffect(() => {
    balance >= 10000
      ? setWidthBoard(139)
      : balance >= 1000
      ? setWidthBoard(132)
      : balance >= 100
      ? setWidthBoard(110)
      : setWidthBoard(95);
  }, [balance]);

  return (
    <div className={className}>
      <SuperEllipse
        r1={0.05}
        r2={0.6}
        height={64}
        width={widthBoard}
        withShadow={false}
        className={classes.board}
      >
        <Balance />
      </SuperEllipse>
    </div>
  );
};
```

**Comment by almond-bongbong** [comment]
@Konstantin9658 
If you're still encountering the issue in version 2.0.2, a possible workaround could be to change the key prop of the SlotCounter component when it's displayed, forcing a recalculation of the width.

This seems to be related to a CSS styling issue, but I'll look into it further.

**Comment by Konstantin9658** [comment]
Hi, Max! Please check your email (if you haven't already), I sent a screen recording, maybe it would help in finding a solution. If you have seen this letter, please let me know. Thank you

**Comment by Konstantin9658** [comment]
oh no, I think I found the reason for this strange behavior and it turned out to be styles. When the modal window is opened, all internal elements have a scale of 0.5 and it calculates based on this value. Excuse me, please.

**Comment by Konstantin9658** [comment]
@almond-bongbong 

But I found this: not in monospace width mode, when moving from 0 to 1, 1 retains the same width as 0 (in my case 14.83px), which creates a distancing effect

![image](https://github.com/almond-bongbong/react-slot-counter/assets/76180339/bebb9850-84c6-4a50-b599-e1332ad5666d)

**Comment by almond-bongbong** [comment]
Unfortunately, there's no way around it. The width is determined based on the widest character within that line (slot). If the width were to change to accommodate the narrower width of the number 1 after transitioning from 0, it would result in a layout shift with each animation. Regrettably, I believe this to be the best approach, but I will consider if there might be another way.

**Comment by Konstantin9658** [comment]
Well, that's a shame. I'll try to think about this question too. Thank you
