### ISSUE TITLE
Alignment Issue With `animateUnchanged` false

### ISSUE THREAD

**Issue by krazibit** [almond-bongbong/react-slot-counter#31]
https://github.com/almond-bongbong/react-slot-counter/assets/23071907/b8aa2003-ed25-43f6-9d8f-4370c103cdb0

As shown in the video above there is a slight alignment issue when `animateUnchanged` is false

**Comment by almond-bongbong** [comment]
I will investigate this immediately to identify and resolve the problem. Thanks for bringing this to our attention.

**Comment by almond-bongbong** [comment]
In the recent 2.2.1 version, I made adjustments to the alignment. Please give it a try and see if it resolves the issue.

**Comment by krazibit** [comment]
Thank @almond-bongbong 
Alignment is better now
