### ISSUE TITLE
`valueClassName` support to `renderDummyList` for enhanced styling flexibility

### ISSUE THREAD

**Issue by daeseong9388** [almond-bongbong/react-slot-counter#38]
I'm currently trying to implement a text gradient effect using `background-clip: text`. However, this effect needs to be applied within the container of the text itself. 

![image](https://github.com/almond-bongbong/react-slot-counter/assets/103937206/c3e72ce7-3d47-4c94-81a3-e746deb695e1)
![image](https://github.com/almond-bongbong/react-slot-counter/assets/103937206/160368a6-7733-4f8d-b1a1-967285a19e1c)

https://github.com/almond-bongbong/react-slot-counter/blob/0e21537c4f74968686d6fe5347e02572cc1aa313/src/components/Slot.tsx#L147C6-L158C14

I would like to request the enhancement of the `renderDummyList` function to accept an additional className prop. This would allow for individual styling of the dummy list items, similar to how `valueClassName` is used for the main value elements. 

Thank you for considering this feature request. I appreciate the work that has been put into the this project and am looking forward to possibly contributing to its further development with this enhancement.

**Comment by almond-bongbong** [comment]
Thank you for your suggestion. This feature seems relatively straightforward to implement and could be beneficial across various use cases. We will work on adding this enhancement promptly.

Thank you once again for your proposal.

**Comment by daeseong9388** [comment]
Thank you for the prompt response and for considering the addition of this feature!! 👍

**Comment by almond-bongbong** [comment]
Version 2.3.0 now includes the numberSlotClassName and numberClassName props. Please check to see if this update addresses your needs, and don't hesitate to let us know if there's anything more you require.
