### ISSUE TITLE
Doesnt work when zoomed in 100%+

### ISSUE THREAD

**Issue by orlandodiaz** [almond-bongbong/react-slot-counter#49]
Animation frozen when zoomed in to more than 100 percent

**Steps to Reproduce**

- Zoom in to 100%+

**Expected Behavior:**

Version of the software/library.
Environment Latest chrome (126)

**Comment by BerendPronkEndeavour** [comment]
@orlandodiaz I'm having the same issue. Why did you complete this issue? Did you find a solution?

**Comment by BerendPronkEndeavour** [comment]
This issue, or at least the one I was having in my last comment, is resolved in version 3.0.1.
