### ISSUE TITLE
Mode "Increase/Decrease"

### ISSUE THREAD

**Issue by Konstantin9658** [almond-bongbong/react-slot-counter#5]
Hello! Great library, I wanted to suggest adding a couple of modes, such as counter increment or decrement. Maybe it's even some kind of direction mode, depending on whether it is added to the number or vice versa?

**Comment by Konstantin9658** [comment]
`import React, { useRef } from 'react';
import SlotCounter, { SlotCounterRef } from 'react-slot-counter';

function App() {
  const counterRef = useRef < SlotCounterRef > null;

  const handleIncreaseOrDecreaseClick = (value: number) => {
    // maybe right here it would be possible to set the direction
    // If _value=1_ the counter is spinning as it is now, that is, from the bottom up
    // If _value=-1_ counter scrolls up and down
    counterRef.current?.startAnimation(value);
  };

  return (
    <div>
      <SlotCounter value={123456} ref={counterRef} />
      <button onClick={handleStartClick}>Start</button>
    </div>
  );
}

export default App;`

But there are situations when there are no controls such as buttons to increase or decrease the counter, for example, data comes from the server after an operation has been completed, for example, replenishment of an account or purchase. Maybe then it would be worth comparing the value before and after, if the value has increased, then the counter spins in one direction, if vice versa, then in the other. I think it looks more real and logical. But this is my personal opinion, you may not agree with it. I hope I made my point clear. Thank you!

**Comment by almond-bongbong** [comment]
Hello,

I appreciate your thoughtful and detailed suggestion. Your idea of enhancing the component with counter increment or decrement modes is quite intriguing. I also find your proposed direction mode, based on whether a number is being added or subtracted, to be a valuable addition. It could indeed make the UI more intuitive and lifelike.

I absolutely agree that comparing the value before and after an operation, such as an account refill or purchase, and then spinning the counter accordingly, makes a lot of sense. This could indeed lead to a more realistic and logical user experience.

So, thank you for your thoughtful insights. I'll definitely look into implementing these improvements to the animation based on your suggestion. Your perspective has been really valuable to me.

Best Regards.

**Comment by Konstantin9658** [comment]
@almond-bongbong Thanks for the quick response! Any idea when this update will be?

**Comment by almond-bongbong** [comment]
@Konstantin9658 
Thank you for your follow-up. I anticipate that these updates, considering their complexity, should be implemented within the next 3-5 days. I’ll do my best to get them rolled out as soon as possible. Stay tuned!

**Comment by Konstantin9658** [comment]
@almond-bongbong  I'm looking forward to

**Comment by almond-bongbong** [comment]
Thank you for your suggestion! We're happy to announce that this feature has been implemented and released in version 1.5.0. Now, the slot counter animation direction will respond based on the value increment or decrement. Please update the package to the latest version and give it a try. As always, your feedback is much appreciated!

**Comment by Konstantin9658** [comment]
Thanks for the work you've done!
