### ISSUE TITLE
Unhandled Runtime Error - RangeError: Invalid array length

### ISSUE THREAD

**Issue by collab-with-tushar-raj** [almond-bongbong/react-slot-counter#52]
![image](https://github.com/user-attachments/assets/c08792b9-caf0-477a-b194-b4fad2614019)

This issue has started coming all of a sudden as my application grows. Everything was working fine initially and now, it has become really annoying because my slot component renders perfectly fine and everything else on the page works as expected. After some time, my page crashes and shows this issue.

This is how I am rendering my component:

![image](https://github.com/user-attachments/assets/f23ed556-c423-4849-b650-a8d082bef9df)

This is the output:

![image](https://github.com/user-attachments/assets/c28a37b2-b14d-41fa-92c7-2b3099b05425)

**Environment:**
- "next": "14.2.3",
- "react": "^18",
- "react-dom": "^18",
- "react-slot-counter": "^3.0.0",

Any idea what could be wrong here?

Thanks!

**Comment by almond-bongbong** [comment]
Thank you for reporting the issue. We will look into the problem immediately.

**Comment by almond-bongbong** [comment]
@collab-with-tushar-raj 

I have identified that the same error occurs when the length of the currentTime.days, currentTime.hours, etc., properties is not 2. Could you please check the value of currentTime?

**Comment by collab-with-tushar-raj** [comment]
> @collab-with-tushar-raj
> 
> I have identified that the same error occurs when the length of the currentTime.days, currentTime.hours, etc., properties is not 2. Could you please check the value of currentTime?

Yes, the length of **currentTime** is 4 (see the output above). Would changing the **startValue** to **0000** fixes this?

**Comment by collab-with-tushar-raj** [comment]
No.

Here is the function I am calling to get the formatted time:

![image](https://github.com/user-attachments/assets/a7b2d72c-a1f8-4fc9-afd2-d2e9aa9dddbb)

And this is how I am updating the state variable:

![image](https://github.com/user-attachments/assets/5a469019-c04f-43b4-b5b2-1c3257fbabb6)

My state variable looks like below:

`  const [currentTime, setCurrentTime] = useState<TimerProps>({
    days: [0, 0],
    hours: [0, 0],
    minutes: [0, 0],
    seconds: [0, 0],
  });`

And I am calling **startCountdownClock** in useEffect.

**Comment by almond-bongbong** [comment]
I apologize, but could you please provide the complete code or a reproducible demo? I'm particularly curious about the part where intervalId is used to clear the interval.

**Comment by almond-bongbong** [comment]
When the remaining minutes and seconds reach 0, the currentTime.minutes becomes -1, causing the error. The suspected part of the code is in the startCountdownClock function, specifically this condition:
```
if (remainingSeconds.current < 0) {
    remainingSeconds.current = 59;
    remainingMinutes.current--;
}
```
![image](https://github.com/user-attachments/assets/60a0282f-999f-4b55-8030-5a6e433340ba)

**Comment by collab-with-tushar-raj** [comment]
Thanks for your help! This made me look my code from another angle. I found few issues and have corrected it. It's working fine now and I hope this issue don't come again.

For your reference, I change else-if to if and clearing the interval when everything becomes zero on the view.

```
  const startCountdownClock = () => {
    intervalId = setInterval(() => {
      remainingSeconds.current--;
      if (
        remainingSeconds.current < 0 &&
        remainingMinutes.current === 0 &&
        remainingHours.current === 0 &&
        remainingDays.current === 0
      ) {
        clearInterval(intervalId);
        return;
      }
      if (remainingSeconds.current < 0) {
        remainingSeconds.current = 59;
        remainingMinutes.current--;
      }
      if (remainingMinutes.current < 0) {
        remainingMinutes.current = 59;
        remainingHours.current--;
      }
      if (remainingHours.current < 0) {
        remainingHours.current = 23;
        remainingDays.current--;
      }
      updateCountdown();
    }, 1000);
  };

```
There is a slight tweak i also did in my useEffect -> instead of calling startCountdownClock there, I moved it inside my calculateRemaingTime function and calling at the last line of if(delta > 0) because clearly, I wanted my countdown timer to be started only when data is in the future.
