### ISSUE TITLE
Counter stuck in update loop when browser zoom is applied

### ISSUE THREAD

**Issue by BerendPronkEndeavour** [almond-bongbong/react-slot-counter#53]
Good morning!

https://github.com/user-attachments/assets/f7ff0dad-de82-4388-b853-47428638fe60

When a user applies custom zoom levels in their browser, the counter will be stuck in some sort of loop. This causes the counter to not update visually at all.

When using a `startValue`, a React key error will also be thrown.

![image](https://github.com/user-attachments/assets/6579e002-730a-47d5-acbe-4793895de822)

**Package version**
3.0.0

**Browser**
Google Chrome 126.0.6478.183
Safari 17.5
(It does work in the latest FireFox)

**System**
MacOS 14.5

**Comment by almond-bongbong** [comment]
Thank you for reporting this issue. We appreciate your attention to detail and your contribution to improving our project. We will address this problem and implement a fix soon. Please stay tuned for updates. If you have any further suggestions or find more issues, feel free to let us know.

Best regards,

**Comment by almond-bongbong** [comment]
Thank you for reporting this issue. We are pleased to inform you that the bug has been fixed in version 3.0.1. Please update to the latest version and let us know if you encounter any further issues.

**Comment by BerendPronkEndeavour** [comment]
@almond-bongbong Thank you so much for this quick response. I confirm the issue has been resolved after updating to version 3.0.1!
