### ISSUE TITLE
There is a problem with startValue and value with the same digits

### ISSUE THREAD

**Issue by xiaogang-xiaogang** [almond-bongbong/react-slot-counter#57]
There is a problem with startValue and value with the same digits, such as 29 and 99. then the 9 can not have an animation

**Comment by almond-bongbong** [comment]
Hello! For the issue you mentioned, the `animateUnchanged` prop might be helpful. 
Would you like to try using this prop? If you still encounter any problems after that, please don't hesitate to let me know.
