### ISSUE TITLE
Disable re-render on window resize

### ISSUE THREAD

**Issue by Alcachofraz** [almond-bongbong/react-slot-counter#61]
Hi, thank you for the amazing package, it looks amazing.

I have but one issue with it. When resizing the browser, the slots will trigger the animation on specific threshold. Is the package configured to have that behavior? Is there a way I can disable it?

I need the animation to trigger only once, and then remain static, regardless of changes to the windows size.

Thanks in advance, and kind regards!

**Comment by almond-bongbong** [comment]
Thank you for your feedback. I'll work on adding that feature!
