### ISSUE TITLE
Feature Request: also support images 

### ISSUE THREAD

**Issue by Leo310** [almond-bongbong/react-slot-counter#8]
Would be cool if you could also support images and not only numbers and strings to create something like this:
![image](https://github.com/almond-bongbong/react-slot-counter/assets/48623649/e97739a4-c52a-41e1-b9cf-9f689ee64857)

So that one would only need to provide the image paths:
```jsx
<SlotCounter
    value={["imagePath1", "imagePath2", "imagePath3"]}
    startValue={["imagePath1", "imagePath1", "imagePath1"]}
    dummyCharacters={["imagePath1", "imagePath2", "imagePath3"]}
/>
```

**Comment by almond-bongbong** [comment]
Thank you for taking the time to provide this excellent suggestion! We truly appreciate it. Rest assured, we will endeavor to release this feature as soon as possible. Please stay tuned. Once again, thank you so much! 👍

**Comment by almond-bongbong** [comment]
Starting from version 1.8.0, we have enhanced the flexibility of the SlotCounter by allowing JSX.Element[] to be passed as a value. This means you can now use images as values! Here's an example of how to use this feature:
```
<SlotCounter
  ref={slot5Ref}
  value={[
    <img className="item" src={item6} alt="" />,
    <img className="item" src={item6} alt="" />,
    <img className="item" src={item6} alt="" />,
  ]}
  startValue={[
    <img className="item" src={item1} alt="" />,
    <img className="item" src={item2} alt="" />,
    <img className="item" src={item3} alt="" />,
  ]}
  dummyCharacters={[
    <img className="item" src={item1} alt="" />,
    <img className="item" src={item2} alt="" />,
    <img className="item" src={item3} alt="" />,
    <img className="item" src={item4} alt="" />,
    <img className="item" src={item5} alt="" />,
    <img className="item" src={item6} alt="" />,
  ]}
/>
```
We hope you find this new functionality useful! As always, feel free to reach out if you have any further questions or suggestions.
